### ISSUE TITLE
Consider replacing country codes with external library

### ISSUE THREAD

**Issue by ivanjaros** [mavolin/standards#1]
Your own country codes take 55kb space. I think it would make more sense to use a dependency(github.com/biter777/countries) which is re-usable by other code as well whilst your own is not(really).

**Comment by mavolin** [comment]
I don't quite understand what that would achieve, maybe you could elaborate on the problem you're facing?

I assume you are talking about the `iban` package, as it is the only one in this lib that imports `iso3166`.
If you need some information about a country that only `github.com/biter777/countries` provides, your easiest solution would be something like this:

```go
myIBAN, err := iban.Parse(someIBAN)
if err != nil {
    // handle err
}

country := countries.ByName(myIBAN.CountryCode.Code)
```

The point of this repo is to provide idiomatic, easy to use implementations for commonly used standards, that all [follow the same pattern](https://github.com/mavolin/standards#each-package-is-the-same), ideally without external deps (which at the current point is the case for all standards). The aim here is to make usage as easy (and predictable) as possible, especially if you already used one of the other implementations.

Since getting the `countries.CountryCode` from an IBAN is a one-liner that doesn't even require error checking, I don't see much of a benefit in not only removing package `iso3166`, but also adding an entirely new dependency.

**Comment by ivanjaros** [comment]
The idea is that people who will use iban validation will also most likely use a library to work with country codes. Linked library is most popular one so it is a sane choice. Your code adds 50kb of uncompiled code into the final binary and redundant for someone who will use library for country codes, as mentioned, which is highly likely, as mentioned.. That's all.
If you want to keep this stand-alone dependency-free library, that's fine.

**Comment by mavolin** [comment]
I would beg to differ (although I obviously don't have any empirical proof) and say that most people would simply use package `iban` to validate IBANs (at least that's what I use it for in the projects where I've used `iban`) and don't actually use any of the extrapolated data.

If right, replacing package `iso3166` with `countries` would create much more of a "bloat" (`countries` being a "bigger" package), which would go unused in the binary.

Lastly, we are truly talking about micro optimisations here. 50kB are not much in this day and age, and I can hardly imagine any use case, where 50kB less would make a difference.
