### ISSUE TITLE
fix(iban): Incorrect national check sum validations for Finland and Estonia. 

### ISSUE THREAD

**Issue by aakavalevich** [mavolin/standards#2]
**Describe the bug**
Valid IBANs from Finland and Estonia are considered invalid due to national checksum validation. 
Here are two random valid IBANs "EE321282973364859699", "FI9775844768617584".   

**Expected behavior**
Valid IBANs are considered valid.

**Error Messages**
If applicable provide error messages and stack traces.

**Versions**
v0.4.0

**Additional context**

**Comment by mavolin** [comment]
Thank you for pointing this out. I've looked at both validators and both were indeed faulty, and unfortunately still passed the old test IBANs:

The validator for Finnish IBANs had an arithmetic error, the Estonian one had a faulty weight.

While at it, I cleaned the code up quite a bit and added a bunch more test IBANs, which luckily showed no other faulty validator before and after cleanup. I've also added the Estonian IBAN you provided to the test cases.

However, the Finnish IBAN you provided seems to be invalid. I've added another Finnish IBAN which confirmed the bug, but the IBAN you provided does not have a valid account number and therefore still fails. While, interestingly, the validator on iban.com (which seems to be the official IBAN site) doesn't seem to recognize the error (and some other also don't), I've found that this site https://www.ibancalculator.com/iban_validieren.html confirms the error in the account number. This maybe, because the check digit is part of the national id (kennitala) and not a proper feature of the IBAN itself and is therefore not implemented by iban.com, but that's just speculation tbh.

It could also mean that newer Finnish Account numbers don't use that same check digit anymore, but Wikipedia still lists the validation and a quick search didn't indicate as much (also it seems weird for a country just to remove a check digit). Therefore, I've kept the validator for now. 

Maybe you have different information? Did you get the IBAN from a "random" site or a (semi-) official source?
